#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
apt update && apt upgrade -y
apt install git -y
_other_installs
git clone $REPO_URL Github_Repo
cd Github_Repo
npm install
node server